version: '3'

services:
  static:
    build:
      context:  ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./sites/:/etc/nginx/sites/ # inject the sites code into the container
      - ./conf/:/etc/nginx/ # inject the conf code into the container
  # test-http:
  #   image: alpine
  #   links:
  #     - static:nginx
