apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: asteroidzoo-org-uk-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: asteroidzoo-org-uk-tls
  dnsNames:
    - asteroidzoo.org.uk
    - "*.asteroidzoo.org.uk"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asteroidzoo.org.uk
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/set-real-ip-from: "10.0.0.0/8"
spec:
  tls:
  - hosts:
    - asteroidzoo.org.uk
    - "*.asteroidzoo.org.uk"
    secretName: asteroidzoo-org-uk-tls
  rules:
  - host: asteroidzoo.org.uk
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: http-frontend
            port:
              number: 80
  - host: "*.asteroidzoo.org.uk"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: http-frontend
            port:
              number: 80
