apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: asteroidzoo-org-uk-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 
  secretName: asteroidzoo-org-uk-tls
  dnsNames:  
    - asteroidzoo.org.uk
    - "*.asteroidzoo.org.uk"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: asteroidzoo.org.uk
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/set-real-ip-from: "10.0.0.0/8"
spec:
  tls:
  - hosts:
    - asteroidzoo.org.uk
    - "*.asteroidzoo.org.uk"
    secretName: asteroidzoo-org-uk-tls
  rules:
  - host: asteroidzoo.org.uk
    http:
      paths:
      - backend:
          serviceName: http-frontend
          servicePort: 80
        path: /(.*)
  - host: "*.asteroidzoo.org.uk"
    http:
      paths:
      - backend:
          serviceName: http-frontend
          servicePort: 80
        path: /(.*)