apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: condorwatch-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 
  secretName: condorwatch-org-tls
  dnsNames:  
    - condorwatch.org
    - "*.condorwatch.org"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: operationwardiary-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 
  secretName: operationwardiary-org-tls
  dnsNames:  
    - operationwardiary.org
    - "*.operationwardiary.org"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: planetfour-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 
  secretName: planetfour-org-tls
  dnsNames:  
    - planetfour.org
    - "*.planetfour.org"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: planktonportal-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 
  secretName: planktonportal-org-tls
  dnsNames:  
    - planktonportal.org
    - "*.planktonportal.org"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: setilive-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 
  secretName: setilive-org-tls
  dnsNames:  
    - setilive.org
    - "*.setilive.org"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: spacewarps-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 
  secretName: spacewarps-org-tls
  dnsNames:  
    - spacewarps.org
    - "*.spacewarps.org"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: volcrowe-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 
  secretName: volcrowe-org-tls
  dnsNames:  
    - volcrowe.org
    - "*.volcrowe.org"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: whats-the-score-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 
  secretName: whats-the-score-org-tls
  dnsNames:  
    - whats-the-score.org
    - "*.whats-the-score.org"
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wormwatchlab-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 
  secretName: wormwatchlab-org-tls
  dnsNames:  
    - wormwatchlab.org
    - "*.wormwatchlab.org"