apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: condorwatch-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: condorwatch-org-tls
  dnsNames:
    - condorwatch.org
    - "*.condorwatch.org"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: condorwatch-org
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/set-real-ip-from: "10.0.0.0/8"
spec:
  tls:
  - hosts:
    - condorwatch.org
    - "*.condorwatch.org"
    secretName: condorwatch-org-tls
  rules:
  - host: condorwatch.org
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: http-frontend
            port:
              number: 80
  - host: "*.condorwatch.org"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: http-frontend
            port:
              number: 80
