apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-fallback
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/set-real-ip-from: "10.0.0.0/8"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: http-frontend
          servicePort: 80
        path: /(.*)