apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: solarstormwatch-com-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: solarstormwatch-com-tls
  dnsNames:
    - solarstormwatch.com
    - "*.solarstormwatch.com"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solarstormwatch.com
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/set-real-ip-from: "10.0.0.0/8"
spec:
  tls:
  - hosts:
    - solarstormwatch.com
    - "*.solarstormwatch.com"
    secretName: solarstormwatch-com-tls
  rules:
  - host: solarstormwatch.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: http-frontend
            port:
              number: 80
  - host: "*.solarstormwatch.com"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: http-frontend
            port:
              number: 80
