apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: spacewarps-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 
  secretName: spacewarps-org-tls
  dnsNames:  
    - spacewarps.org
    - "*.spacewarps.org"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spacewarps-org
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/set-real-ip-from: "10.0.0.0/8"
spec:
  tls:
  - hosts:
    - spacewarps.org
    - "*.spacewarps.org"
    secretName: spacewarps-org-tls
  rules:
  - host: spacewarps.org
    http:
      paths:
      - backend:
          serviceName: http-frontend
          servicePort: 80
        path: /(.*)
  - host: "*.spacewarps.org"
    http:
      paths:
      - backend:
          serviceName: http-frontend
          servicePort: 80
        path: /(.*)