apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: thetriangulumproject-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 
  secretName: thetriangulumproject-org-tls
  dnsNames:  
    - thetriangulumproject.org
    - "*.thetriangulumproject.org"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: thetriangulumproject.org
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/set-real-ip-from: "10.0.0.0/8"
spec:
  tls:
  - hosts:
    - thetriangulumproject.org
    - "*.thetriangulumproject.org"
    secretName: thetriangulumproject-org-tls
  rules:
  - host: thetriangulumproject.org
    http:
      paths:
      - backend:
          serviceName: http-frontend
          servicePort: 80
        path: /(.*)
  - host: "*.thetriangulumproject.org"
    http:
      paths:
      - backend:
          serviceName: http-frontend
          servicePort: 80
        path: /(.*)
