apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcamgorongosa-org-tls
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: wildcamgorongosa-org-tls
  dnsNames:
    - wildcamgorongosa.org
    - www.wildcamgorongosa.org
    - lab.wildcamgorongosa.org
    - learn.wildcamgorongosa.org
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wildcamgorongosa.org
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/set-real-ip-from: "10.0.0.0/8"
spec:
  tls:
  - hosts:
    - wildcamgorongosa.org
    - www.wildcamgorongosa.org
    - lab.wildcamgorongosa.org
    - learn.wildcamgorongosa.org
    secretName: wildcamgorongosa-org-tls
  rules:
  - host: wildcamgorongosa.org
    http:
      paths:
      - backend:
          serviceName: http-frontend
          servicePort: 80
        path: /(.*)
  - host: "www.wildcamgorongosa.org"
    http:
      paths:
      - backend:
          serviceName: http-frontend
          servicePort: 80
        path: /(.*)
  - host: "lab.wildcamgorongosa.org"
    http:
      paths:
      - backend:
          serviceName: http-frontend
          servicePort: 80
        path: /(.*)
  - host: "learn.wildcamgorongosa.org"
    http:
      paths:
      - backend:
          serviceName: http-frontend
          servicePort: 80
        path: /(.*)
