name: Apply Modified Ingresses

on:
  push:
    tags:
      - production-ingress
  workflow_dispatch:

jobs:
  apply_ingresses:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set the target AKS cluster
      uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_AKS }}'
        cluster-name: microservices
        resource-group: kubernetes

    - name: Get last applied ingress hash
      run: |
        echo "CURRENT_INGRESS_HASH=$(git show-ref --tags | grep production-ingress-release | cut -d ' ' -f 1)" >> $GITHUB_ENV

    - name: Apply modified ingress files
      run: |
        output=$(git diff --name-only $CURRENT_INGRESS_HASH ${{ github.sha }})
        echo $output | while read -r line
          do
            if [[ $line = *"kubernetes/ingress/"* ]]; then
              kubectl apply -f $line
            fi
          done

  update_ingress_tag:
    runs-on: ubuntu-latest
    needs: apply_ingresses
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Update Ingress Tag
      run: |
        git tag production-ingress-release
        git push --force origin --tags
