name: Deploy HTTP Frontend Production

on:
  push:
    tags:
      - production-release
  workflow_dispatch:

jobs:
  deploy_nginx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Set the target AKS cluster
      uses: Azure/aks-set-context@v4.0.0
      with:
        creds: '${{ secrets.AZURE_AKS }}'
        cluster-name: microservices
        resource-group: kubernetes

    - name: Modify & apply template
      run: |
        sed "s/__IMAGE_TAG__/${{ github.sha }}/g" ./kubernetes/deployment-production.tmpl \
          | kubectl apply -f -

  deploy_slack_notification:
    name: Deploy Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: deploy_nginx
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: deploy_nginx
      status: ${{ needs.deploy_nginx.result }}
      title: "HTTP Frontend production deploy complete"
      title_link: "https://static.zooniverse.org"
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
